name: Update Blocked List

on:
  schedule:
    # Запуск каждые 6 часов
    - cron: '0 */6 * * *'
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Download the latest file
        run: |
          mkdir -p files
          curl -L https://github.com/runetfreedom/russia-blocked-geosite/raw/refs/heads/release/ru-blocked.txt -o files/ru-blocked.txt

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add files/ru-blocked.txt
          # Проверка на наличие изменений, чтобы не плодить пустые коммиты
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update ru-blocked.txt $(date -u)" && git push)
